= Spring Boot, Camel and AMQP Sample

This sample shows how to connect a Camel Spring-Boot application to an AMQP Endpoint as consumer
and consume any message published to "amqp:queue:telemetry.cortex.train.window.applicatienaam1",
then using https://access.redhat.com/documentation/en-us/red_hat_fuse/7.8/html-single/apache_camel_development_guide/index#MsgRout-RecipientList[Recipient List pattern] it push the message to two (2) destinations "amqp:queue:telemetry.cortex.train.window.applicatienaam1.zone-a", and "amqp:queue:telemetry.cortex.train.window.applicatienaam1.zone-b"

== Setting up the OpenShift environment

It is assumed that:

* Your OpenShift environment is configured for Fabric8 Maven Workflow, if not you can refer to my blog post https://github.com/rahmed-rh/fuse_on_OCP_7.5[Understand Fuse 7.5 on OpenShift].
** You can easily setup the fuse on openshift using script https://raw.githubusercontent.com/rahmed-rh/fuse_on_OCP_7.5/master/scripts/install_fis_7.5.sh[install_fis_7.5.sh]
* AMQ Interconnect is installed on OpenShift environment,if not you can refer to my blog post https://github.com/rahmed-rh/amq-interconnect-mesh-demo[Amq Interconnect Mesh Demo]


== Running the example on Local Machine (Spring Boot)

. Modify the amqp.serviceName key in application.properties to the value you of Messaging Endpoint
. Then the following command will run the application

[source,bash]
----
mvn spring-boot:run -Dspring.profiles.active=dev
----

== Running the example in OpenShift

. The following command will package your app and run it on OpenShift (For more info on Fuse on Openshift, please refer to https://github.com/rahmed-rh/fuse_on_OCP_7.x[Understand Fuse 7.x on OpenShift]):
+
[source,bash]
----
mvn clean fabric8:deploy -Popenshift
----
+
. To list all the running pods:
+
[source,bash]
----
oc get pods
----
